/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectochat.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author samo_
 */
public class VistaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        
    }
    
    public void setMensajeChatGeneral(String mensaje){
        jTextAreaChatGeneral.setText(jTextAreaChatGeneral.getText() + "\n------------------------------------------\n" + mensaje);
    }
    
    public void setVaciarCajaTexto(){
        jTextFieldEnviar.setText("");
    }
    public void setTextoEstado(String estado){
        jLabelEstadoValor.setText(estado);
    }
    
    public String getTextoEnviar(){
        return jTextFieldEnviar.getText();
    }
    
    public void addControlador(ActionListener e){
        jButtonEnviar.addActionListener(e);
        jTextFieldEnviar.addActionListener(e);
        jButtonSalir.addActionListener(e);
        
        jButtonEnviar.setActionCommand("enviar");
        jTextFieldEnviar.setActionCommand("enviar");
        jButtonSalir.setActionCommand("salir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneChatGeneral = new javax.swing.JScrollPane();
        jTextAreaChatGeneral = new javax.swing.JTextArea();
        jPanelSurTools = new javax.swing.JPanel();
        jPanelEstado = new javax.swing.JPanel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelEstadoValor = new javax.swing.JLabel();
        jPanelSalir = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanelEnviarMensaje = new javax.swing.JPanel();
        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTextAreaChatGeneral.setColumns(20);
        jTextAreaChatGeneral.setRows(5);
        jTextAreaChatGeneral.setEnabled(false);
        jScrollPaneChatGeneral.setViewportView(jTextAreaChatGeneral);

        add(jScrollPaneChatGeneral, java.awt.BorderLayout.CENTER);

        jPanelSurTools.setLayout(new java.awt.BorderLayout());

        jLabelEstado.setText("Estado: ");
        jPanelEstado.add(jLabelEstado);
        jPanelEstado.add(jLabelEstadoValor);

        jPanelSurTools.add(jPanelEstado, java.awt.BorderLayout.WEST);

        jButtonSalir.setText("Salir");
        jPanelSalir.add(jButtonSalir);

        jPanelSurTools.add(jPanelSalir, java.awt.BorderLayout.EAST);

        jPanelEnviarMensaje.setLayout(new java.awt.BorderLayout());
        jPanelEnviarMensaje.add(jTextFieldEnviar, java.awt.BorderLayout.CENTER);

        jButtonEnviar.setText("Enviar");
        jPanelEnviarMensaje.add(jButtonEnviar, java.awt.BorderLayout.LINE_END);

        jPanelSurTools.add(jPanelEnviarMensaje, java.awt.BorderLayout.NORTH);

        add(jPanelSurTools, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoValor;
    private javax.swing.JPanel jPanelEnviarMensaje;
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelSurTools;
    private javax.swing.JScrollPane jScrollPaneChatGeneral;
    private javax.swing.JTextArea jTextAreaChatGeneral;
    private javax.swing.JTextField jTextFieldEnviar;
    // End of variables declaration//GEN-END:variables
}
