/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectochat.vista;

import java.awt.event.ActionListener;

/**
 *
 * @author samo_
 */
public class VistaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        
    }
    
    public void setMensajeChatGeneral(String mensaje){
        jTextAreaChatGeneral.setText(jTextAreaChatGeneral.getText() + "\n------------------------------------------\n" + mensaje);
    }
    
    public void setVaciarCajaTexto(){
        jTextFieldEnviar.setText("");
    }
    
    public String getTextoEnviar(){
        return jTextFieldEnviar.getText();
    }
    
    public void addControlador(ActionListener e){
        jButtonConectar.addActionListener(e);
        jButtonDesconectar.addActionListener(e);
        jButtonUsuarios.addActionListener(e);
        jButtonEnviar.addActionListener(e);
        jTextFieldEnviar.addActionListener(e);
        jButtonNombre.addActionListener(e);
        
        jButtonNombre.setActionCommand("nombre");
        jButtonConectar.setActionCommand("conectar");
        jButtonDesconectar.setActionCommand("desconectar");
        jButtonUsuarios.setActionCommand("usuarios");
        jButtonEnviar.setActionCommand("enviar");
        jTextFieldEnviar.setActionCommand("enviar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneChatGeneral = new javax.swing.JScrollPane();
        jTextAreaChatGeneral = new javax.swing.JTextArea();
        jPanelSurTools = new javax.swing.JPanel();
        jPanelEnviarMensaje = new javax.swing.JPanel();
        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jToolBarHerramientas = new javax.swing.JToolBar();
        jButtonConectar = new javax.swing.JButton();
        jButtonDesconectar = new javax.swing.JButton();
        jButtonUsuarios = new javax.swing.JButton();
        jButtonNombre = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTextAreaChatGeneral.setColumns(20);
        jTextAreaChatGeneral.setRows(5);
        jTextAreaChatGeneral.setEnabled(false);
        jScrollPaneChatGeneral.setViewportView(jTextAreaChatGeneral);

        add(jScrollPaneChatGeneral, java.awt.BorderLayout.CENTER);

        jPanelSurTools.setLayout(new java.awt.BorderLayout());

        jPanelEnviarMensaje.setLayout(new java.awt.BorderLayout());
        jPanelEnviarMensaje.add(jTextFieldEnviar, java.awt.BorderLayout.CENTER);

        jButtonEnviar.setText("Enviar");
        jPanelEnviarMensaje.add(jButtonEnviar, java.awt.BorderLayout.LINE_END);

        jPanelSurTools.add(jPanelEnviarMensaje, java.awt.BorderLayout.NORTH);

        add(jPanelSurTools, java.awt.BorderLayout.PAGE_END);

        jToolBarHerramientas.setRollover(true);

        jButtonConectar.setText("Conectar");
        jButtonConectar.setFocusable(false);
        jButtonConectar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonConectar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarHerramientas.add(jButtonConectar);

        jButtonDesconectar.setText("Desconectar");
        jToolBarHerramientas.add(jButtonDesconectar);

        jButtonUsuarios.setText("Usuarios");
        jToolBarHerramientas.add(jButtonUsuarios);

        jButtonNombre.setText("Cambiar nombre");
        jButtonNombre.setFocusable(false);
        jButtonNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNombre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBarHerramientas.add(jButtonNombre);

        add(jToolBarHerramientas, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonDesconectar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonNombre;
    private javax.swing.JButton jButtonUsuarios;
    private javax.swing.JPanel jPanelEnviarMensaje;
    private javax.swing.JPanel jPanelSurTools;
    private javax.swing.JScrollPane jScrollPaneChatGeneral;
    private javax.swing.JTextArea jTextAreaChatGeneral;
    private javax.swing.JTextField jTextFieldEnviar;
    private javax.swing.JToolBar jToolBarHerramientas;
    // End of variables declaration//GEN-END:variables
}
