/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectochat.vista;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import proyectochat.modelo.Clientes;

/**
 *
 * @author samo_
 */
public class VistaPrincipal extends javax.swing.JPanel {

    private Clientes clientes;
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        setListaUsuarios(new ArrayList<String>());
        
    }
    
    public void setMensajeChatGeneral(String mensaje){
        jTextAreaChatGeneral.setText(jTextAreaChatGeneral.getText() + "\n------------------------------------------\n" + mensaje);
    }
    public void setListaUsuarios(ArrayList<String> usuarios){
        
        if (usuarios.isEmpty()){
            jListUsuarios.setListData(new String[]{"No hay usuarios conectados"});
        }else{
            jListUsuarios.setListData(clientes.getNickClientes());
            
        }
    }
    public void setVaciarChatGeneral(){
        jTextAreaChatGeneral.setText("");
    }
    public void setUnableDesconectar(boolean b){
        jButtonParar.setEnabled(b);
    }
    public void setBtnPararText(String texto){
        jButtonParar.setText(texto);
    }
    public void setVaciarCajaTexto(){
        jTextFieldEnviar.setText("");
    }
    public void setDireccion(String direccion){
        jLabelValorDireccion.setText(direccion);
    }
    public void setPuerto(int puerto){
        jLabelValorPuerto.setText(String.valueOf(puerto));
    }
    
    public String getTextoEnviar(){
        return jTextFieldEnviar.getText();
    }
    
    public void addControlador(ActionListener e){
        jButtonEnviar.addActionListener(e);
        jTextFieldEnviar.addActionListener(e);
        jButtonMostrarUsuario.addActionListener(e);
        jButtonParar.addActionListener(e);
        jButtonSalir.addActionListener(e);
        
        jButtonEnviar.setActionCommand("enviar");
        jTextFieldEnviar.setActionCommand("enviar");
        jButtonMostrarUsuario.setActionCommand("mostrar");
        jButtonParar.setActionCommand("parar");
        jButtonSalir.setActionCommand("salir");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneChatGeneral = new javax.swing.JScrollPane();
        jTextAreaChatGeneral = new javax.swing.JTextArea();
        jPanelSurTools = new javax.swing.JPanel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonParar = new javax.swing.JButton();
        jButtonMostrarUsuario = new javax.swing.JButton();
        jPanelSalir = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanelEnviarMensaje = new javax.swing.JPanel();
        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jPanelUsuariosConectados = new javax.swing.JPanel();
        jLabelUsuarioConectado = new javax.swing.JLabel();
        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        jListUsuarios = new javax.swing.JList<>();
        jPanelInformacion = new javax.swing.JPanel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelValorDireccion = new javax.swing.JLabel();
        jLabelPuerto = new javax.swing.JLabel();
        jLabelValorPuerto = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTextAreaChatGeneral.setColumns(20);
        jTextAreaChatGeneral.setRows(5);
        jTextAreaChatGeneral.setEnabled(false);
        jScrollPaneChatGeneral.setViewportView(jTextAreaChatGeneral);

        add(jScrollPaneChatGeneral, java.awt.BorderLayout.CENTER);

        jPanelSurTools.setLayout(new java.awt.BorderLayout());

        jButtonParar.setText("Desconectar Clientes");
        jPanelOpciones.add(jButtonParar);

        jButtonMostrarUsuario.setText("Mostrar Usuarios");
        jPanelOpciones.add(jButtonMostrarUsuario);

        jPanelSurTools.add(jPanelOpciones, java.awt.BorderLayout.CENTER);

        jButtonSalir.setText("Salir");
        jPanelSalir.add(jButtonSalir);

        jPanelSurTools.add(jPanelSalir, java.awt.BorderLayout.EAST);

        jPanelEnviarMensaje.setLayout(new java.awt.BorderLayout());
        jPanelEnviarMensaje.add(jTextFieldEnviar, java.awt.BorderLayout.CENTER);

        jButtonEnviar.setText("Enviar");
        jPanelEnviarMensaje.add(jButtonEnviar, java.awt.BorderLayout.LINE_END);

        jPanelSurTools.add(jPanelEnviarMensaje, java.awt.BorderLayout.NORTH);

        add(jPanelSurTools, java.awt.BorderLayout.PAGE_END);

        jPanelUsuariosConectados.setRequestFocusEnabled(false);
        jPanelUsuariosConectados.setLayout(new java.awt.BorderLayout());

        jLabelUsuarioConectado.setText("Usuarios conectados: ");
        jPanelUsuariosConectados.add(jLabelUsuarioConectado, java.awt.BorderLayout.NORTH);

        jScrollPaneUsuarios.setViewportView(jListUsuarios);

        jPanelUsuariosConectados.add(jScrollPaneUsuarios, java.awt.BorderLayout.CENTER);

        add(jPanelUsuariosConectados, java.awt.BorderLayout.LINE_END);

        jPanelInformacion.setLayout(new java.awt.GridLayout(1, 0));

        jLabelDireccion.setText("Dirección: ");
        jPanelInformacion.add(jLabelDireccion);
        jPanelInformacion.add(jLabelValorDireccion);

        jLabelPuerto.setText("Puerto: ");
        jPanelInformacion.add(jLabelPuerto);
        jPanelInformacion.add(jLabelValorPuerto);

        add(jPanelInformacion, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonMostrarUsuario;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelPuerto;
    private javax.swing.JLabel jLabelUsuarioConectado;
    private javax.swing.JLabel jLabelValorDireccion;
    private javax.swing.JLabel jLabelValorPuerto;
    private javax.swing.JList<String> jListUsuarios;
    private javax.swing.JPanel jPanelEnviarMensaje;
    private javax.swing.JPanel jPanelInformacion;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelSurTools;
    private javax.swing.JPanel jPanelUsuariosConectados;
    private javax.swing.JScrollPane jScrollPaneChatGeneral;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    private javax.swing.JTextArea jTextAreaChatGeneral;
    private javax.swing.JTextField jTextFieldEnviar;
    // End of variables declaration//GEN-END:variables
}
