/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectochat.vista;

/**
 *
 * @author samo_
 */
public class VistaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneChatGeneral = new javax.swing.JScrollPane();
        jTextAreaChatGeneral = new javax.swing.JTextArea();
        jPanelSurTools = new javax.swing.JPanel();
        jPanelEstado = new javax.swing.JPanel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelEstadoValor = new javax.swing.JLabel();
        jPanelOpciones = new javax.swing.JPanel();
        jButtonParar = new javax.swing.JButton();
        jButtonMostrarUsuario = new javax.swing.JButton();
        jPanelSalir = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanelEnviarMensaje = new javax.swing.JPanel();
        jTextFieldEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jPanelUsuariosConectados = new javax.swing.JPanel();
        jLabelUsuarioConectado = new javax.swing.JLabel();
        jScrollPaneUsuarios = new javax.swing.JScrollPane();
        jTextAreaUsuario = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jTextAreaChatGeneral.setColumns(20);
        jTextAreaChatGeneral.setRows(5);
        jTextAreaChatGeneral.setEnabled(false);
        jScrollPaneChatGeneral.setViewportView(jTextAreaChatGeneral);

        add(jScrollPaneChatGeneral, java.awt.BorderLayout.CENTER);

        jPanelSurTools.setLayout(new java.awt.BorderLayout());

        jLabelEstado.setText("Estado: ");
        jPanelEstado.add(jLabelEstado);
        jPanelEstado.add(jLabelEstadoValor);

        jPanelSurTools.add(jPanelEstado, java.awt.BorderLayout.WEST);

        jPanelOpciones.add(jButtonParar);

        jButtonMostrarUsuario.setText("Mostrar Usuarios");
        jPanelOpciones.add(jButtonMostrarUsuario);

        jPanelSurTools.add(jPanelOpciones, java.awt.BorderLayout.CENTER);

        jButtonSalir.setText("Salir");
        jPanelSalir.add(jButtonSalir);

        jPanelSurTools.add(jPanelSalir, java.awt.BorderLayout.EAST);

        jPanelEnviarMensaje.setLayout(new java.awt.BorderLayout());
        jPanelEnviarMensaje.add(jTextFieldEnviar, java.awt.BorderLayout.CENTER);

        jButtonEnviar.setText("Enviar");
        jPanelEnviarMensaje.add(jButtonEnviar, java.awt.BorderLayout.LINE_END);

        jPanelSurTools.add(jPanelEnviarMensaje, java.awt.BorderLayout.NORTH);

        add(jPanelSurTools, java.awt.BorderLayout.PAGE_END);

        jPanelUsuariosConectados.setRequestFocusEnabled(false);
        jPanelUsuariosConectados.setLayout(new java.awt.BorderLayout());

        jLabelUsuarioConectado.setText("Usuarios conectados: ");
        jPanelUsuariosConectados.add(jLabelUsuarioConectado, java.awt.BorderLayout.NORTH);

        jTextAreaUsuario.setColumns(20);
        jTextAreaUsuario.setRows(5);
        jTextAreaUsuario.setEnabled(false);
        jScrollPaneUsuarios.setViewportView(jTextAreaUsuario);

        jPanelUsuariosConectados.add(jScrollPaneUsuarios, java.awt.BorderLayout.CENTER);

        add(jPanelUsuariosConectados, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonMostrarUsuario;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoValor;
    private javax.swing.JLabel jLabelUsuarioConectado;
    private javax.swing.JPanel jPanelEnviarMensaje;
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JPanel jPanelOpciones;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelSurTools;
    private javax.swing.JPanel jPanelUsuariosConectados;
    private javax.swing.JScrollPane jScrollPaneChatGeneral;
    private javax.swing.JScrollPane jScrollPaneUsuarios;
    private javax.swing.JTextArea jTextAreaChatGeneral;
    private javax.swing.JTextArea jTextAreaUsuario;
    private javax.swing.JTextField jTextFieldEnviar;
    // End of variables declaration//GEN-END:variables
}
